//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PuntosColombia.Recursos {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensajes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensajes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PuntosColombia.Recursos.Mensajes", typeof(Mensajes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la lista A.
        /// </summary>
        internal static string En_la_lista_A {
            get {
                return ResourceManager.GetString("En_la_lista_A", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En la lista B.
        /// </summary>
        internal static string En_la_lista_B {
            get {
                return ResourceManager.GetString("En_la_lista_B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ha ocurrido un error inesperado, se adjunta la traza a continuación.
        /// </summary>
        internal static string ErrorInesperado {
            get {
                return ResourceManager.GetString("ErrorInesperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La Lista B debe tener mayor número de elementos que la Lista A.
        /// </summary>
        internal static string ListaB_debe_tener_mas_elementos_ListaA {
            get {
                return ResourceManager.GetString("ListaB_debe_tener_mas_elementos_ListaA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No se encontraron diferencias en las listas.
        /// </summary>
        internal static string NoHayDiferenciasEnListas {
            get {
                return ResourceManager.GetString("NoHayDiferenciasEnListas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número mínimo de ítems es inferior al esperado.
        /// </summary>
        internal static string NumeroItemsInferiorAlEsperado {
            get {
                return ResourceManager.GetString("NumeroItemsInferiorAlEsperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El número máximo de ítems es superior al esperado.
        /// </summary>
        internal static string NumeroMaximoSuperaEsperado {
            get {
                return ResourceManager.GetString("NumeroMaximoSuperaEsperado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hay al menos un valor que está en una lista pero que no esta en la otra.
        /// </summary>
        internal static string NumeroXNoEstaEnY {
            get {
                return ResourceManager.GetString("NumeroXNoEstaEnY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to El rango de valores es superior a 100.
        /// </summary>
        internal static string RangoValoresSuperiorA100 {
            get {
                return ResourceManager.GetString("RangoValoresSuperiorA100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alguna de las listas se encuentran vacías o los datos que ingreso no son valores validos para el proceso.
        /// </summary>
        internal static string UnaListaEstaVacia {
            get {
                return ResourceManager.GetString("UnaListaEstaVacia", resourceCulture);
            }
        }
    }
}
